apiVersion: v1
kind: Namespace
metadata:
  name: ns-retailpulse
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-um-config
  namespace: ns-retailpulse
data:
  # This application.yaml is adjusted for K8s (note the datasource URL!).
  application.yaml: |
    server.port: 8083

    auth:
      enabled: true
      origin: "http://localhost:4200"
      jwt.key.set.uri: http://app-iam:8081/oauth2/jwks
    
    spring:
      datasource:
        url: jdbc:mysql://mysql-auth:3306/identity_access
        username: root
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
    
      jpa:
        hibernate:
          ddl-auto: none
        database-platform: org.hibernate.dialect.MySQL8Dialect
        show-sql: false
    
    logging:
      level:
        root: INFO
        org:
          springframework:
            security: INFO
        com.retailpulse: DEBUG
      file:
        name: logs/user-management.log

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-um
  namespace: ns-retailpulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-um
  template:
    metadata:
      labels:
        app: app-um
    spec:
      containers:
        - name: app-um
          image: rp-um-service:v0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          # Option A: rely on application.yaml mounted from ConfigMap
          volumeMounts:
            - name: app-config
              mountPath: /config
          env:
            # Make Spring read /config/application.yaml first
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "file:/config/"

            # Hard override to avoid any "localhost" in baked config
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-auth:3306/identity_access"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-auth-secret
                  key: MYSQL_ROOT_PASSWORD

            - name: SERVER_PORT
              value: "8083"
          readinessProbe:
            tcpSocket:
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 20
      volumes:
        - name: app-config
          configMap:
            name: app-um-config
            items:
              - key: application.yaml
                path: application.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: app-um
  namespace: ns-retailpulse
spec:
  type: NodePort
  selector:
    app: app-um
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30083
