apiVersion: v1
kind: Secret
metadata:
  name: secret-mysql-user
  namespace: ns-retailpulse
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: RPUserDB

---
apiVersion: v1
data:
  init.sql: "-- CREATE DATABASE identity_access;\r\n-- GRANT ALL PRIVILEGES ON identity_access.*
    TO 'root'@'localhost';\r\n-- FLUSH PRIVILEGES;\r\n\r\nCREATE TABLE IF NOT EXISTS
    users (\r\n    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,\r\n    username
    VARCHAR(45) NOT NULL UNIQUE,\r\n    password VARCHAR(255) NOT NULL,\r\n    name
    VARCHAR(255),\r\n    email VARCHAR(255),\r\n    enabled INT NOT NULL\r\n);\r\n\r\nCREATE
    TABLE authorities (\r\n    id BIGINT AUTO_INCREMENT PRIMARY KEY,\r\n    username
    VARCHAR(255) NOT NULL,\r\n    authority VARCHAR(255) NOT NULL,\r\n    CONSTRAINT
    fk_authorities_user FOREIGN KEY (username) REFERENCES users(username) ON DELETE
    CASCADE\r\n);\r\n\r\n-- Password: password (encoded using BCrypt)\r\nINSERT INTO
    users (username, password, name, email, enabled)\r\nVALUES ('superadmin', '$2a$10$Icdy05HD6OXmfVEaX3Kk0OTN3p/DYz95GNluZqvD5HTCGxLAdbP/C',
    'Kent Clark', 'kentc@rpulse.com', 1);\r\n\r\nINSERT INTO authorities (username,
    authority)\r\nVALUES ('superadmin', 'ADMIN');\r\n\r\nINSERT INTO users (username,
    password, name, email, enabled)\r\nVALUES ('batman', '$2a$10$Icdy05HD6OXmfVEaX3Kk0OTN3p/DYz95GNluZqvD5HTCGxLAdbP/C',
    'Bruce Wayne', 'brucew@rpulse.com', 1);\r\n\r\nINSERT INTO authorities (username,
    authority)\r\nVALUES ('batman', 'CASHIER');\r\n\r\nINSERT INTO users (username,
    password, name, email, enabled)\r\nVALUES ('ironman', '$2a$10$Icdy05HD6OXmfVEaX3Kk0OTN3p/DYz95GNluZqvD5HTCGxLAdbP/C',
    'Tony Stark', 'tonys@rpulse.com', 1);\r\n\r\nINSERT INTO authorities (username,
    authority)\r\nVALUES ('ironman', 'CASHIER');\r\n\r\nINSERT INTO users (username,
    password, name, email, enabled)\r\nVALUES ('blackwidow', '$2a$10$Icdy05HD6OXmfVEaX3Kk0OTN3p/DYz95GNluZqvD5HTCGxLAdbP/C',
    'Natasha', 'natasha@rpulse.com', 1);\r\n\r\nINSERT INTO authorities (username,
    authority)\r\nVALUES ('blackwidow', 'MANAGER');\r\n\r\nCREATE TABLE oauth2_registered_client
    (\r\n                                          id varchar(100) NOT NULL,\r\n                                          client_id
    varchar(100) NOT NULL,\r\n                                          client_id_issued_at
    timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,\r\n                                          client_secret
    varchar(200) DEFAULT NULL,\r\n                                          client_secret_expires_at
    timestamp,\r\n                                          client_name varchar(200)
    NOT NULL,\r\n                                          client_authentication_methods
    varchar(1000) NOT NULL,\r\n                                          authorization_grant_types
    varchar(1000) NOT NULL,\r\n                                          redirect_uris
    varchar(1000) DEFAULT NULL,\r\n                                          post_logout_redirect_uris
    varchar(1000) DEFAULT NULL,\r\n                                          scopes
    varchar(1000) NOT NULL,\r\n                                          client_settings
    varchar(2000) NOT NULL,\r\n                                          token_settings
    varchar(2000) NOT NULL,\r\n                                          PRIMARY KEY
    (id)\r\n);\r\n\r\nCREATE TABLE oauth2_authorization (\r\n                                      id
    varchar(100) NOT NULL,\r\n                                      registered_client_id
    varchar(100) NOT NULL,\r\n                                      principal_name
    varchar(200) NOT NULL,\r\n                                      authorization_grant_type
    varchar(100) NOT NULL,\r\n                                      authorized_scopes
    varchar(1000) DEFAULT NULL,\r\n                                      attributes
    blob DEFAULT NULL,\r\n                                      state varchar(500)
    DEFAULT NULL,\r\n                                      authorization_code_value
    blob DEFAULT NULL,\r\n                                      authorization_code_issued_at
    timestamp ,\r\n                                      authorization_code_expires_at
    timestamp ,\r\n                                      authorization_code_metadata
    blob DEFAULT NULL,\r\n                                      access_token_value
    blob DEFAULT NULL,\r\n                                      access_token_issued_at
    timestamp ,\r\n                                      access_token_expires_at timestamp
    ,\r\n                                      access_token_metadata blob DEFAULT
    NULL,\r\n                                      access_token_type varchar(100)
    DEFAULT NULL,\r\n                                      access_token_scopes varchar(1000)
    DEFAULT NULL,\r\n                                      oidc_id_token_value blob
    DEFAULT NULL,\r\n                                      oidc_id_token_issued_at
    timestamp ,\r\n                                      oidc_id_token_expires_at
    timestamp ,\r\n                                      oidc_id_token_metadata blob
    DEFAULT NULL,\r\n                                      refresh_token_value blob
    DEFAULT NULL,\r\n                                      refresh_token_issued_at
    timestamp ,\r\n                                      refresh_token_expires_at
    timestamp ,\r\n                                      refresh_token_metadata blob
    DEFAULT NULL,\r\n                                      user_code_value blob DEFAULT
    NULL,\r\n                                      user_code_issued_at timestamp ,\r\n
    \                                     user_code_expires_at timestamp ,\r\n                                      user_code_metadata
    blob DEFAULT NULL,\r\n                                      device_code_value
    blob DEFAULT NULL,\r\n                                      device_code_issued_at
    timestamp ,\r\n                                      device_code_expires_at timestamp
    ,\r\n                                      device_code_metadata blob DEFAULT NULL,\r\n
    \                                     PRIMARY KEY (id)\r\n);\r\n\r\nCREATE TABLE
    oauth2_authorization_consent (\r\n                                              registered_client_id
    varchar(100) NOT NULL,\r\n                                              principal_name
    varchar(200) NOT NULL,\r\n                                              authorities
    varchar(1000) NOT NULL,\r\n                                              PRIMARY
    KEY (registered_client_id, principal_name)\r\n);"
kind: ConfigMap
metadata:
  name: cm-mysql-user-init
  namespace: ns-retailpulse

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-user-pvc
  namespace: ns-retailpulse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-rp-user
  namespace: ns-retailpulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-rp-user
  template:
    metadata:
      labels:
        app: mysql-rp-user
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-mysql-user
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: secret-mysql-user
                  key: MYSQL_DATABASE
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: init-sql-file
              mountPath: /docker-entrypoint-initdb.d
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-user-pvc
        - name: init-sql-file
          configMap:
            name: cm-mysql-user-init

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-rp-user 
  namespace: ns-retailpulse
spec:
  selector:
    app: mysql-rp-user
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30305
  type: NodePort