apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-rp-user-app
  namespace: ns-retailpulse
data:
  application.yaml: |
    server:
      port: 8082

    auth:
      enabled: false
      origin: "http://localhost:4200" # "http://localhost:30080" #
      jwt:
        key:
          set:
            uri: http://app-iam:8081/oauth2/jwks

    spring:
      datasource:
        url: jdbc:mysql://mysql-rp-user:3306/RPUserDB
        username: root
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver

      jpa:
        hibernate:
          ddl-auto: update
        database-platform: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
    
    logging:
      level:
        root: INFO
        org:
          springframework:
            security: TRACE
        com.retailpulse: DEBUG
      file:
        name: logs/rp-user.log

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-rp-user
  namespace: ns-retailpulse
  labels:
    app: deploy-rp-user  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-rp-user
  template:
    metadata:
      labels:
        app: deploy-rp-user
    spec:
      containers:
      - image: docker.io/casperyap/rp-user-app:v0.1.0
        name: app-rp-user
        imagePullPolicy: Always
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        resources: {}
      volumes:
      - name: config-volume
        configMap:
          name: cm-rp-user-app

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: deploy-rp-user
  name: svc-rp-user
spec:
  selector:
    app: deploy-rp-user
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
    nodePort: 30082 
  type: NodePort